name: calculator
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.0
  share: ^2.0.1
  splashscreen: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons: 
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/calc_icon.png"

flutter:
  fonts:
    - family: Calculator
      fonts:
        - asset: fonts/calculator.ttf
  assets:
    - assets/images/calc_icon.png

  uses-material-design: true
